rankTheBoysApp/pools/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length, ValidationError
from rankTheBoysApp.models import Pool, User

class CreatePoolForm(FlaskForm):
    poolname = StringField('PoolName', validators=[DataRequired(), Length(min=2, max=20)])
    submit = SubmitField('Create')

    def validate_poolname(self, poolname):
        ## if there is a value, it'll be here. if not, it will jsut return none
        poolname = Pool.query.filter_by(name=poolname.data).first()
        ## if user is none, won't hit this conditional
        if poolname:
            raise ValidationError('A pool with that name has already been created!')

class JoinPoolForm(FlaskForm):
    poolname = StringField('PoolName', validators=[DataRequired(), Length(min=2, max=20)])
    search = SubmitField('Search')
    
    def validate_pool(self, poolname):
        poolname = Pool.query.filter_by(name=poolname.data).first()
        if not poolname:
            raise ValidationError('That pool doesn\'t exist!')

rankTheBoysApp/pools/routes.py
from crypt import methods
from rankTheBoysApp.pools.forms import CreatePoolForm, JoinPoolForm
from rankTheBoysApp import db
from rankTheBoysApp.models import Pool, User, UserPool
from rankTheBoysApp.users.forms import MatchForm
from rankTheBoysApp.users.utils import calculateEloAmount
from flask import Blueprint, flash, redirect, render_template, url_for, request
from flask_login import login_required, current_user
from random import randint

thePools = Blueprint('pools', __name__)

@thePools.route("/pools", methods=['GET', 'POST'])
@login_required
def pools():
    form = CreatePoolForm()
    form1 = JoinPoolForm()
    if form.submit.data and form.validate():
        pool = Pool(name=form.poolname.data)
        #userpool = UserPool(pool_id = pool.id, user_id=current_user.id, rating=1200)
        current_user.pools.append(pool)
        db.session.add(pool)
        db.session.commit()
        db.session
        flash('Your pool has been created!', 'success')
        return redirect(url_for('pools.pools'))
    if form1.search.data and form1.validate():
        pool = Pool.query.filter_by(name=form1.poolname.data).first()
        current_user.pools.append(pool)
        db.session.commit()
        flash('You have joined the pool!')
        return redirect(url_for('pools.pools'))
    return render_template('pools.html', title='Pools', form=form, form1=form1)

@thePools.route("/pools/<string:poolname>", methods=['GET', 'POST'])
@login_required
def leaderboard(poolname):
    page = request.args.get('page', 1, type=int)
    pool = Pool.query.filter_by(name=poolname).first()
    users = db.session.query(User, UserPool).join(User).filter(UserPool.pool_id==pool.id).order_by(UserPool.rating.desc()).all()
    return render_template('leaderboard.html', users=users, pool=pool)

@thePools.route("/pools/logmatch/<string:poolname>", methods = ['GET', 'POST'])
@login_required
def log_match(poolname):
    pool = Pool.query.filter_by(name=poolname).first()
    form = MatchForm()
    if form.validate_on_submit():
        opponent = User.query.filter_by(username=form.whoYouPlayed.data).first()
        if form.didYouWin.data:
            calculateEloAmount(current_user.id, opponent.id, pool.id)
        else:
            calculateEloAmount(opponent.id, current_user.id, pool.id)
        flash('Match logged and rankings updated!')
        return redirect(url_for('pools.pools'))
    return render_template('match.html', form = form)

rankTheBoysApp/users/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request
from rankTheBoysApp.users.forms import LoginForm, RegistrationForm, UpdateAccountForm, ResetPasswordForm, RequestResetForm
from flask_login import current_user, login_user, login_required, logout_user
from rankTheBoysApp.models import User
from rankTheBoysApp import db, bcrypt
from rankTheBoysApp.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form = form)

rankTheBoysApp/templates/about.html
{% extends "layout.html" %}
{%block content%}
<div class="content-section">
    <h1> About </h1>

    <p> EloPoolRater was founded by somebody who eventually became sick and tired of not having a system to refer to when it came to bumper pool bragging rights.
    </p>
    <p> Angered by his competitors' tendencies to self-proclaim themselves as champions of mythical status, he furiously researched ways to rate players' relative skill levels.
        He stumbled upon the legendary Elo rating system, and decided to implement it because he honestly had nothing better to do with his time (he still has nothing better to do with his time, which is why he sent you this website).
    </p>
    <p> If you find yourself consistently dominating your peers in whatever meaningless game you waste your time playing whilst deprived of the validation of a leaderboard, consider utilizing this resource.</p>
    <p> If you're curious about how the system works, and maybe even would like to read about a more advanced modification to it called the Glicko system, visit <a href="https://www.chess.com/terms/elo-rating-chess" target="_blank">this page.</a></p>
    <p> (This website is a work in progress) </p>
</div>
{% endblock %}

rankTheBoysApp/templates/account.html
{% extends "layout.html" %}
{%block content%}

<div class="content-section">
    <div class="media">
      <img class="rounded-circle account-img" src="{{ image_file }}">
      <div class="media-body">
        <h2 class="account-heading">{{ current_user.username }}</h2>
        <p class="text-secondary">{{ current_user.email }}</p>
      </div>
    </div>
        <form method="POST" action = "" enctype="multipart/form-data">
            {{  form.hidden_tag() }}
            <fieldset class="form_group">
                <legend class="border_bottom mb-4"> Account Info </legend>
                <div class = "form-group">
                    {{  form.username.label(class="form=control-label") }}
                    {% if form.username.errors %}
                        {{form.username(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>
                                    {{ error }}
                                </span>
                            {% endfor %}
                        </div>
                    {% else %}
                    {{  form.username(class="form-control form-control-lg") }}
                    {%endif%}
                </div>
                <div class = "form-group">
                    {{  form.email.label(class="form=control-label") }}
                    {% if form.email.errors %}
                        {{form.email(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span class="text-danger">
                                    {{ error }}
                                </span>
                            {% endfor %}
                            </div>
                    {% else %}
                    {{  form.email(class="form-control form-control-lg") }}
                    {%endif%}
                </div>
                <div class = "form-group">
                    {{  form.picture.label() }}
                    {{ form.picture(class="form-control-file")}}
                    {% if form.picture.errors %}
                    {% for error in form.picture.errors %}
                        <span>
                            {{ error }}
                        </span>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>   
</div>

{% endblock %}

rankTheBoysApp/templates/home.html
{% extends "layout.html" %}
{%block content%}
<div class="content-section">
    {% if current_user.is_authenticated %} 
    
        <h1>Time to play!</h1>
        <p>Navigate to "Pools" in the navbar to find a pool!</p>
        <p>Create a pool and fill it with you and your competitors.  Each time you face-off, log the result.  The rating system will adjust your rating accordingly and will rank the field.</p>
    {% else %}
        <h1> Login to utilize </h1>
        <p>Login to join and participate in pools!</p>
        <p>Create a pool and fill it with you and your competitors.  Each time you face-off, log the result.  The rating system will adjust your rating accordingly and will rank the field.</p>
    {%endif%}
</div>
{% endblock %}

rankTheBoysApp/templates/layout.html
<!DOCTYPE html>
<html>
<head>  
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <link rel="stylesheet" type ="text/css" href="{{url_for('static', filename='main.css')}}">
    
    {% if title %}  
    <title> {{title}} </title>
    {% else %}
    <title> EloPoolRater </title>
    {% endif %}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand" href="/"> EloPoolRater </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="/">Home</a>
                <a class="nav-item nav-link" href="/about">About</a>
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                  <a class="nav-item nav-link" href="/account">Account</a>
                  <a class="nav-item nav-link" href="/pools">Pools</a>
                  <a class="nav-item nav-link" href="/logout">Sign out</a>
                {% else %}
                  <a class="nav-item nav-link" href="/login">Login</a>
                  <a class="nav-item nav-link" href="/register">Register</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
      </header>
    
      <main role="main" class="container">
        <div class="row">
          <div class="col-md-12">
            {% with messages = get_flashed_messages(with_categories=true) %}
              {%if messages %} 
                {% for category, message in messages %}
                  <div class="alert alert-{{ category }}">
                    {{ message }}
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
          </div>
        </div>
      </main>

      <div class="footer">
        <p> &copy Michele Catani, 2022 </p>
      </div>
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>

rankTheBoysApp/templates/leaderboard.html
{% extends "layout.html" %}
{%block content%}
    <h1 class="mb-3"> {{pool.name}}'s Leaderboard </h1>
    {% for user, userpool in users %}
    <div class="content-section">
        <div media-content-section>
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + user.image_file) }}">
            <div class="media-body">
                <div class="article-metadata">
                    <h3> {{ user.username }}</h3>
                    <p> Rating: {{ userpool.rating }} <p>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
{% endblock %}

rankTheBoysApp/templates/login.html
{% extends "layout.html" %}
{%block content%}

    <div class= "content-section">
        <form method="POST" action = "">
            {{  form.hidden_tag() }}
            <fieldset class="form_group">
                <legend class="border_bottom mb-4"> Log In </legend>
                
                <div class = "form-group">
                    {{  form.email.label(class="form=control-label") }}
                    {% if form.email.errors %}
                        {{form.email(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>
                                    {{ error }}
                                </span>
                            {% endfor %}
                            </div>
                    {% else %}
                    {{  form.email(class="form-control form-control-lg") }}
                    {%endif%}
                </div>
                <div class = "form-group">
                    {{  form.password.label(class="form=control-label") }}
                    {% if form.password.errors %}
                        {{form.password(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>
                                    {{ error }}
                                </span>
                            {% endfor %}
                        </div>
                    {% else %}
                    {{  form.password(class="form-control form-control-lg") }}
                    {%endif%}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <div class="text-muted" ml-2>
                <a href="{{url_for('users.reset_request')}}"> Forgot Password </a>
            </div>
        </form>      
    </div>

    <div class="border-top pt-3">
        <small class="text-muted">
            Need an account? <a class="ml-2" href="{{ url_for('users.register')}}">  
                Register
            </a>
        </small>
    </div>
{% endblock %}

rankTheBoysApp/templates/match.html
{% extends "layout.html" %}
{%block content%}

    <div class= "content-section">
        <form method="POST" action = "">
            {{  form.hidden_tag() }}
            <fieldset class="form_group">
                <legend class="border_bottom mb-4"> Log Match</legend>
                
                <div class = "form-group">
                    {{  form.whoYouPlayed.label(class="form=control-label") }}
                    {% if form.whoYouPlayed.errors %}
                        {{form.whoYouPlayed(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.whoYouPlayed.errors %}
                                <span>
                                    {{ error }}
                                </span>
                            {% endfor %}
                            </div>
                    {% else %}
                    {{  form.whoYouPlayed(class="form-control form-control-lg") }}
                    {%endif%}
                </div>
                <div class="form-check">
                    {{ form.didYouWin(class="form-check-input") }}
                    {{ form.didYouWin.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>      
    </div>
{% endblock %}

rankTheBoysApp/templates/pools.html
{% extends "layout.html" %}
{%block content%}
    <h1>Pools</h1>
    <div class="content-section">
        <div class="media-body">
            <h2 class="account-heading"> {{ current_user.username }}'s Pools </h>
        </div>
        <div>
            {% if current_user.pools %} 
                {% for pool in current_user.pools %}
                <div class="media content-section">
                    <h3>{{ pool.name }}</h3>
                    <p>Your rating: 1200 TODO </p>
                    <p>Your ranking: 1/5 TODO </p>
                    <p><a class="mr-2" href="{{ url_for('pools.leaderboard', poolname=pool.name)}}">Leaderboard</a></p>
                    <p><a class="mr-2" href="{{ url_for('pools.log_match', poolname=pool.name)}}">Log a match (Fix, add dropdown)</a></p>
                </div>
                {% endfor %}
            {% else %}
                <p>You currently aren't in any pools!</p>
            {% endif %}
        </div>
        <div class="media content-section">
            <form method="POST" action = "">
                {{  form.hidden_tag() }}
                <fieldset class="form_group">
                    <legend class="border_bottom mb-4"> Create Pool</legend>
                    
                    <div class = "form-group">
                        {{  form.poolname.label(class="form=control-label") }}
                        {% if form.poolname.errors %}
                            {{form.poolname(class="form-control form-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.poolname.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                                </div>
                        {% else %}
                        {{  form.poolname(class="form-control form-control-lg") }}
                        {%endif%}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>
        </div>
        <div class="media content-section">
            <form method="POST" action = "">
                {{  form1.hidden_tag() }}
                <fieldset class="form_group">
                    <legend class="border_bottom mb-4"> Join Pool</legend>
                    <div class = "form-group">
                        {{  form1.poolname.label(class="form=control-label") }}
                        {% if form1.poolname.errors %}
                            {{form1.poolname(class="form-control form-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form1.poolname.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                                </div>
                        {% else %}
                        {{  form1.poolname(class="form-control form-control-lg") }}
                        {%endif%}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form1.search(class="btn btn-outline-info") }}
                </div>
            </form>
        </div>
    </div>
{% endblock %}

rankTheBoysApp/templates/register.html
{% extends "layout.html" %}
{%block content%}

 
    <div class= "content-section">
        <form method="POST" action = "">
            {{  form.hidden_tag() }}
            <fieldset class="form_group">
                <legend class="border_bottom mb-4"> Join Today </legend>
                <div class = "form-group">
                    {{  form.username.label(class="form=control-label") }}
                    {% if form.username.errors %}
                        {{form.username(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>
                                    {{ error }}
                                </span>
                            {% endfor %}
                        </div>
                    {% else %}
                    {{  form.username(class="form-control form-control-lg") }}
                    {%endif%}
                </div>
                <div class = "form-group">
                    {{  form.email.label(class="form=control-label") }}
                    {% if form.email.errors %}
                        {{form.email(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>
                                    {{ error }}
                                </span>
                            {% endfor %}
                            </div>
                    {% else %}
                    {{  form.email(class="form-control form-control-lg") }}
                    {%endif%}
                </div>
                <div class = "form-group">
                    {{  form.password.label(class="form=control-label") }}
                    {% if form.password.errors %}
                        {{form.password(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>
                                    {{ error }}
                                </span>
                            {% endfor %}
                        </div>
                    {% else %}
                    {{  form.password(class="form-control form-control-lg") }}
                    {%endif%}
                </div>
                <div class = "form-group">
                    {{  form.confirm_password.label(class="form=control-label") }}
                    {% if form.confirm_password.errors %}
                        {{form.confirm_password(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>
                                    {{ error }}
                                </span>
                            {% endfor %}
                        </div>
                    {% else %}
                    {{  form.confirm_password(class="form-control form-control-lg") }}
                    {%endif%}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>      
    </div>

    <div class="border-top pt-3">
        <small class="text-muted">
            Already have an account? <a class="ml-2" href="{{ url_for('users.login')}}">  
                Sign In
            </a>
        </small>
    </div>
{% endblock %}

rankTheBoysApp/templates/reset_request.html
{% extends "layout.html" %}
{%block content%}
    <div class= "content-section">
        <form method="POST" action = "">
            {{  form.hidden_tag() }}
            <fieldset class="form_group">
                <legend class="border_bottom mb-4"> Reset Password </legend>
                
                <div class = "form-group">
                    {{  form.email.label(class="form=control-label") }}
                    {% if form.email.errors %}
                        {{form.email(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>
                                    {{ error }}
                                </span>
                            {% endfor %}
                            </div>
                    {% else %}
                    {{  form.email(class="form-control form-control-lg") }}
                    {%endif%}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>      
    </div>
{% endblock %}

rankTheBoysApp/templates/reset_token.html
{% extends "layout.html" %}
{%block content%}
    <div class= "content-section">
        <form method="POST" action = "">
            {{  form.hidden_tag() }}
            <fieldset class="form_group">
                <legend class="border_bottom mb-4"> Reset Password </legend>
                
                <div class = "form-group">
                    {{  form.password.label(class="form=control-label") }}
                    {% if form.password.errors %}
                        {{form.password(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>
                                    {{ error }}
                                </span>
                            {% endfor %}
                            </div>
                    {% else %}
                    {{  form.password(class="form-control form-control-lg") }}
                    {%endif%}
                </div>
                <div class = "form-group">
                    {{  form.confirm_password.label(class="form=control-label") }}
                    {% if form.confirm_password.errors %}
                        {{form.confirm_password(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>
                                    {{ error }}
                                </span>
                            {% endfor %}
                            </div>
                    {% else %}
                    {{  form.confirm_password(class="form-control form-control-lg") }}
                    {%endif%}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>      
    </div>
{% endblock %}